CREATE TABLE USER (
    RollNumber varchar(10) NOT NULL PRIMARY KEY,
    Email varchar(255) NOT NULL,
    Username varchar(255) NOT NULL UNIQUE,
    Password varchar(255) NOT NULL
);

INSERT INTO USER VALUES ('710019104303', 'winson@gmail.com', 'winson', 'winson@123');
SELECT * FROM USER;

-- 
UPDATE USER SET Email='winson@gmail.com' WHERE RollNumber='710019104303';
SELECT * FROM USER;
-- 
DELETE FROM USER WHERE ROLLNUMBER='710019104303';
SELECT * FROM USER;
-- 
DELETE FROM USER WHERE USERNAME='winson';
SELECT * FROM USER;